name: Backend CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: curlafhair
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, pdo_mysql

      - name: Install Composer Dependencies
        run: |
          cd backend
          composer install --no-interaction --prefer-dist

      - name: Setup Laravel
        run: |
          cp backend/.env.example backend/.env
          php backend/artisan key:generate

      - name: Run Tests
        run: php backend/artisan test
